package com.bw.forwardweek2.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bw.forwardweek2.model.dao.ClassifyTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASSIFY_TABLE".
*/
public class ClassifyTableDao extends AbstractDao<ClassifyTable, Void> {

    public static final String TABLENAME = "CLASSIFY_TABLE";

    /**
     * Properties of entity ClassifyTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ClassifyJson = new Property(0, String.class, "classifyJson", false, "CLASSIFY_JSON");
    }


    public ClassifyTableDao(DaoConfig config) {
        super(config);
    }
    
    public ClassifyTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSIFY_TABLE\" (" + //
                "\"CLASSIFY_JSON\" TEXT);"); // 0: classifyJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSIFY_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClassifyTable entity) {
        stmt.clearBindings();
 
        String classifyJson = entity.getClassifyJson();
        if (classifyJson != null) {
            stmt.bindString(1, classifyJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClassifyTable entity) {
        stmt.clearBindings();
 
        String classifyJson = entity.getClassifyJson();
        if (classifyJson != null) {
            stmt.bindString(1, classifyJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ClassifyTable readEntity(Cursor cursor, int offset) {
        ClassifyTable entity = new ClassifyTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // classifyJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClassifyTable entity, int offset) {
        entity.setClassifyJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ClassifyTable entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ClassifyTable entity) {
        return null;
    }

    @Override
    public boolean hasKey(ClassifyTable entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
