package com.bw.forwardweek2.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bw.forwardweek2.model.dao.CommodityTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMODITY_TABLE".
*/
public class CommodityTableDao extends AbstractDao<CommodityTable, Void> {

    public static final String TABLENAME = "COMMODITY_TABLE";

    /**
     * Properties of entity CommodityTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommodityJson = new Property(0, String.class, "CommodityJson", false, "COMMODITY_JSON");
    }


    public CommodityTableDao(DaoConfig config) {
        super(config);
    }
    
    public CommodityTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMODITY_TABLE\" (" + //
                "\"COMMODITY_JSON\" TEXT);"); // 0: CommodityJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMODITY_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CommodityTable entity) {
        stmt.clearBindings();
 
        String CommodityJson = entity.getCommodityJson();
        if (CommodityJson != null) {
            stmt.bindString(1, CommodityJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CommodityTable entity) {
        stmt.clearBindings();
 
        String CommodityJson = entity.getCommodityJson();
        if (CommodityJson != null) {
            stmt.bindString(1, CommodityJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CommodityTable readEntity(Cursor cursor, int offset) {
        CommodityTable entity = new CommodityTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // CommodityJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CommodityTable entity, int offset) {
        entity.setCommodityJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CommodityTable entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CommodityTable entity) {
        return null;
    }

    @Override
    public boolean hasKey(CommodityTable entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
